algoritmo "TesteParImpar"
// Função :
// Autor : Dihego
// Data : 18/05/2023
// Seção de Declarações 
var

   numero : inteiro

inicio

      escreval("Digite um numero:")
      leia(numero)
      escreval
      se(numero mod 2 = 0) entao
          escreval("O número ", numero, " é par")
      senao
          escreval("O número ", numero, " é impar")
      fimse


fimalgoritmo
