algoritmo "Tabuada"
// Função :
// Autor : Dihego
// Data : 22/05/2023
// Seção de Declarações 
var

   numero, contador : inteiro

inicio

     escreval("Digite o número para gerar a tabuada:")
     leia(numero)
     escreval
     
     contador <- 1
     
     enquanto (contador < 11) faca
          escreval(numero, " x ",contador, " = ", (numero * contador))
          contador <- contador + 1
     fimenquanto

fimalgoritmo
