algoritmo "TestandoRepita2"
// Função :
// Autor : Dihego
// Data : 22/05/2023
// Seção de Declarações 
var

   numero, quantia : inteiro

inicio

      repita
           escreval("Digite um número até chegar ao 40:")
           escreval("Número atual: ", numero)
           leia(quantia)
           numero <- numero + quantia
      ate numero >= 40
      
      escreval
      escreval("Contagem acima de 40!")

fimalgoritmo
