algoritmo "EnquantoFaca"
// Função :
// Autor : Dihego
// Data : 21/05/2023
// Seção de Declarações 
var

   numero, soma : inteiro

inicio

      enquanto numero <> 5 faca

           escreval("É preciso digitar o número '5':")
           leia(numero)
           soma <- soma + numero

      fimenquanto
      
      escreval("A soma de todos os números digitados é: ", soma)

fimalgoritmo
