algoritmo "TestandoIf4"
// Função :
// Autor : Dihego
// Data : 18/05/2023
// Seção de Declarações 
var

   numero : real

inicio

      escreval("Digite um numero de 0 a 10:")
      leia(numero)
      escreval
      
      se(numero >= 1) e (numero <= 10) entao
           escreval("O numero ", numero, " está entre 0 e 10")
      senao
           escreval("O numero ", numero, " não está entre 0 e 10")
      fimse

fimalgoritmo
